### ISSUE TITLE
 Could not find 'bundler' (2.1.4) required by your /app/Gemfile.lock. (Gem::GemNotFoundException)

### ISSUE THREAD

**Issue by giapbnv-0886** [rails-sqlserver/heroku-buildpack-freetds#10]
cannot install  bundler when i deploy with sql server.. May you help me?

**Comment by bf4** [comment]
Sorry, there's not enough information to help you.  

We don't know anything about your situation except presumably the bundler version you're trying to use.

And this buildpack should have nothing to do with that.
