### ISSUE TITLE
$PATH should be escaped

### ISSUE THREAD

**Issue by kwlockwo** [rails-sqlserver/heroku-buildpack-freetds#13]
https://github.com/rails-sqlserver/heroku-buildpack-freetds/blob/master/bin/compile#L86 `$PATH` should be escaped otherwise the PATH expanded at the .profile.d script is created rather than when the script runs on the dyno booting.

This is causing the `PATH` to be set at the time the `.profile.d` the script runs to be lost.

**Comment by kwlockwo** [comment]
Pretty sure this is not the only instance of a variable having this issue.  `LD_LIBRARY_PATH` will also have the same problem.

**Comment by gaffneyc** [comment]
I opened #12 last week which fixes $PATH at least. I think you're right that LD_LIBRARY_PATH (and LD_RUN_PATH and LIBRARY_PATH) will all get clobbered though I'm not sure how common those are.

**Comment by kwlockwo** [comment]
I have seen `LIBRARY_PATH` used, `LD_RUN_PATH` not so much.  Should be escaped all the same.

**Comment by schneems** [comment]
There's a larger issue where the PATH from build time are being picked up and preserved into runtime even though the two have different path structures https://github.com/rails-sqlserver/heroku-buildpack-freetds/issues/17

**Comment by bf4** [comment]
@metaskills I think this issue is collecting some good potential collaborators :) Anyone want commit?

**Comment by bf4** [comment]
Closed by https://github.com/rails-sqlserver/heroku-buildpack-freetds/pull/21
